# Generated by Django 5.1.7 on 2025-06-09 18:18

import django.db.models.deletion
import django_quill.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='🏷️ Название бренда')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='🌍 Страна-производитель')),
                ('website', models.URLField(blank=True, null=True, verbose_name='🔗 Веб-сайт')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='🔍 Подробный')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='🎨 Логотип')),
            ],
            options={
                'verbose_name': '🅱 Бренд',
                'verbose_name_plural': '🅱 Бренды продукта',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='♻️ Название бренда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='📝 Описание')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': '♻️ Категории продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить')),
                ('name', models.CharField(help_text='Не более 255 символов', max_length=255, verbose_name='💊 Название продукта')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='📝 Описание')),
                ('detail', django_quill.fields.QuillField(blank=True, null=True, verbose_name='🛠 Подробный')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_images/', verbose_name='📸 Изображение')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.brandmodel', verbose_name='🏷️ Бренд')),
                ('category', models.ManyToManyField(related_name='product_category', to='product.categorymodel', verbose_name='📂 Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': '🛍 Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='📸 Изображение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Фотографии продукта',
                'verbose_name_plural': '📸 Фотографии продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить')),
                ('package_quantity', models.CharField(help_text='Не более 25 символов', max_length=25, verbose_name='🧺 Количество в упаковке')),
                ('product_code', models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True, verbose_name='🏷️ Код товара')),
                ('shipping_weight', models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True, verbose_name='⚖️\tВес при доставке')),
                ('dimensions', models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True, verbose_name='📐 Размеры')),
                ('price', models.DecimalField(decimal_places=0, help_text='Валюта Узбекистан СУМ*', max_digits=10, verbose_name='💸 Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='📦 В наличии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Количество в упаковке',
                'verbose_name_plural': 'Количество в упаковке',
            },
        ),
    ]
