# Generated by Django 5.1.7 on 2025-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': '🅱️ Бренды продукта'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': '♻️ Категории продукта'},
        ),
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'verbose_name': 'Фотографии продукта', 'verbose_name_plural': 'Фотографии продукта'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': '🛍 Продукты'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(help_text='Не более 255 символов', max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Валюта Узбекистан СУМ*', max_digits=10),
        ),
    ]
