# Generated by Django 5.1.7 on 2025-03-15 12:38

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brandmodel_options_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': '🅱 Бренды продукта'},
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='detail',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
