# Generated by Django 5.1.7 on 2025-04-22 01:59

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brandmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='category_images/'),
        ),
    ]
