# Generated by Django 5.1.7 on 2025-04-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_categorymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductVariantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_quantity', models.CharField(help_text='Не более 25 символов', max_length=25)),
                ('product_code', models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True)),
                ('shipping_weight', models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Валюта Узбекистан СУМ*', max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Количество в упаковке',
                'verbose_name_plural': 'Количество в упаковке',
            },
        ),
    ]
