# Generated by Django 5.1.7 on 2025-04-22 06:27

import django_quill.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productmodel_price_remove_productmodel_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
