# Generated by Django 5.1.7 on 2025-04-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productmodel_allowed_alter_productmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariantsmodel',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
