# Generated by Django 5.1.7 on 2025-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brandmodel_allowed_categorymodel_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать'),
        ),
    ]
