# Generated by Django 5.1.7 on 2025-04-22 17:14

import django.db.models.deletion
import django_quill.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_brandmodel_allowed_alter_categorymodel_allowed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': '🅱 Бренд', 'verbose_name_plural': '🅱 Бренды продукта'},
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='🌍 Страна-производитель'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='🔍 Подробный'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='🎨 Логотип'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='🏷️ Название бренда'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='🔗 Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='📝 Описание'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='♻️ Название бренда'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='📸 Изображение'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.brandmodel', verbose_name='🏷️ Бренд'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='product.categorymodel', verbose_name='📂 Категории'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='📝 Описание'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='detail',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='🛠 Подробный'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(help_text='Не более 255 символов', max_length=255, verbose_name='💊 Название продукта'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True, verbose_name='📐 Размеры'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='package_quantity',
            field=models.CharField(help_text='Не более 25 символов', max_length=25, verbose_name='🧺 Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Валюта Узбекистан СУМ*', max_digits=10, verbose_name='💸 Цена'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='product_code',
            field=models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True, verbose_name='🏷️ Код товара'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='shipping_weight',
            field=models.CharField(blank=True, help_text='Не более 25 символов', max_length=25, null=True, verbose_name='⚖️\tВес при доставке'),
        ),
        migrations.AlterField(
            model_name='productvariantsmodel',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='📦 В наличии'),
        ),
    ]
