# Generated by Django 5.1.7 on 2025-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_brandmodel_options_alter_brandmodel_allowed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'verbose_name': 'Фотографии продукта', 'verbose_name_plural': '📸 Фотографии продукта'},
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='allowed',
            field=models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить'),
        ),
    ]
