# Generated by Django 5.1.7 on 2025-05-24 08:14

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productimagemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_images/', verbose_name='📸 Изображение'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_images/', verbose_name='📸 Изображение'),
        ),
    ]
