# Generated by Django 5.1.7 on 2025-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productimagemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='📸 Изображение'),
        ),
    ]
