# Generated by Django 5.1.7 on 2025-06-09 18:18

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='🎠 Названия')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='🎠 Названия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='📝 Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='🔗 Ссылка')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='carousel/', verbose_name='📸 Изображение')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': '🎠 Карусели',
            },
        ),
    ]
