# Generated by Django 5.1.7 on 2025-06-08 12:16

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='С помощью этого поля вы разрешаете сайту публиковать', verbose_name='📢 Разрешить публикацию')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='🎠 Названия')),
            ],
        ),
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': '🎠 Карусели'},
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='📝 Описание'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='carousel/', verbose_name='📸 Изображение'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='🔗 Ссылка'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='🎠 Названия'),
        ),
    ]
