# Generated by Django 5.1.7 on 2025-05-25 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='📦 Данные заказа')),
                ('status', models.CharField(choices=[('new', '🆕 Новый'), ('confirmed', '✅ Подтвержден'), ('cancelled', '❌ Отменен')], default='new', max_length=10, verbose_name='📌 Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='🕒 Дата создания')),
            ],
            options={
                'verbose_name': '📄 Чек',
                'verbose_name_plural': '📄 Все чеки',
            },
        ),
    ]
