# Generated by Django 5.1.7 on 2025-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='🚚 Стоимость доставки'),
        ),
    ]
